config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get "/login", to: "home#login"

  devise_for :managers,
  path: "managers",
  controllers: {
    sessions: 'managers/sessions',
    registrations: 'managers/registrations'
  }

  devise_for :customers,
    path: "customers",
    controllers: {
      sessions: 'customers/sessions',
      registrations: 'customers/registrations'
  }

  resources :buffets, only: [:new, :create, :show]
  get '/buffet', to: "buffets#index", as: :manager_root


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cade Buffet?</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <div class="container">

      <header class="container-fluid d-flex justify-content-between p-2">
        <div class="align-content-center">
            <h1 class="m-auto"> <%= link_to  "Cadê Buffet?", @root_path, class:"" %> </h1>
        </div>

        <div class="d-flex flex-column justify-content-center">
          <% if @customer_app %>
            <div class="">Olá, <%= current_customer.name %></div>
            <%= button_to  "Sair", destroy_customer_session_path, method: :delete, form_class: "align-self-end" %>
          <% end %>
          <% if @manager_app %>
            <div class="">Olá, <%= current_manager.name %></div>
            <%= button_to  "Sair", destroy_manager_session_path, method: :delete, form_class: "align-self-end" %>
          <% end %>
          <% if @user_app %>
              <%= link_to  "Entrar", login_path, class:"" %>
          <% end %>
        </div>

      </header>

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <div class="container-fluid pt-1 pb-3">
        <%= yield %>
      </div>

    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>